name: "CLA Check"
on:
  repository_dispatch:
    types: trigger-cla-check
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
        uses: ockam-network/cla-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSISTANCE_GITHUB_TOKEN: ${{ secrets.PERSISTANCE_GITHUB_TOKEN }}
        with:
          path-to-signatures: 'cla-signers.json'
          path-to-cla-document: 'https://www.ockam.io/learn/guides/contributions/cla'
          branch: 'master'
          persistance-repository: 'contributors'
          empty-commit-flag: false
          blockchain-storage-flag: false
      - name: "Trigger"
        env:
          PERSISTANCE_GITHUB_TOKEN: ${{ secrets.PERSISTANCE_GITHUB_TOKEN }}
        run: |
          curl -H "Accept: application/vnd.github.mercy-preview+json" \
            -H "Authorization: token ${PERSISTANCE_GITHUB_TOKEN}" \
            --request POST \
            --data '{"event_type": "trigger-cla-check"}' \
            https://api.github.com/repos/ockam-network/did-method-spec/dispatches
